# Generated by Django 2.2 on 2019-04-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0002_auto_20190420_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='nickname',
        ),
    ]
